spring:
  # 配置应用名称
  application:
    name: stock-management
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 服务端接口
server:
  port: 9999
  servlet:
    context-path: /
# Mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: priv.backend.entity

